### ISSUE TITLE
Epic: ipld-eth-db-validator recap and remaining tasks

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-db-validator#3]
Currently the validator supports validation of state, header, and tx data by 

1. Loading header from the Postgres database (at block N): https://github.com/vulcanize/ipld-eth-db-validator/blob/main/pkg/validator/validator.go#L184
2. Loading transactions from the Postgres database (at block N) https://github.com/vulcanize/ipld-eth-db-validator/blob/main/pkg/validator/validator.go#L196
3. Initializing an EVM with a stateDB with the state in Postgres (at block N) https://github.com/vulcanize/ipld-eth-db-validator/blob/main/pkg/validator/validator.go#L203
4. Applying those transactions on top of the state in the Postgres database (at block N) https://github.com/vulcanize/ipld-eth-db-validator/blob/main/pkg/validator/validator.go#L206
5. Confirming that the resulting state root matches the state root seen in the header in LevelDB at block N+1 https://github.com/vulcanize/ipld-eth-db-validator/blob/main/pkg/validator/validator.go#L123

It only performs this validation at some depth away from the head of the chain (the most recent header in the Postgres database) https://github.com/vulcanize/ipld-eth-db-validator/blob/main/pkg/validator/validator.go#L109, but it only currently does this in a one-off manner rather than repeating this process while trailing behind the head as it progresses.

Additionally, it is not currently doing any validation of the receipts, logs, and log trie data.

Todo:

- [x] Make the process an ongoing trailing process
- [ ] Add capabilities for validating the remaining data
  - [x] Validating referential integrity in the data
  - [ ] Validating ipld-eth-db state key lookup access pattern
- [ ] Integration testing/benchmarking
  - [x] Add integration tests
  - [ ] Use tx-spammer in the integration tests

Related: https://github.com/vulcanize/tx_spammer/issues/10

**Comment by i-norden** [comment]
We may want to use: https://github.com/vulcanize/tx_spammer/issues/9

**Comment by i-norden** [comment]
Validation process should validate both trie traversal access pattern and state leaf key lookup access pattern.

To add to this, for the state transition we currently use ipfs.ethdb to plugin to geth's EVM. So this uses the trie traversal access pattern on top of public.blocks- it does not touch (validate) the content of the state_cids/storage_cids tables.

We could create an execution environment which instead accesses state using direct lookup with state_leaf_key/storage_leaf_key against the state_cids/storage_cids tables. Successfully performing the expected state transition with this access pattern provides some degree of validation of the data in state_cids/storage_cids.

**Comment by roysc** [comment]
Since the geth EVM indexes and accesses trie nodes by hash, not leaf key, we won't be able to directly query by leaf keys in `ipfs-ethdb` (while still leveraging the EVM for executing state transitions). I think our options are:
1. Within `Database.Get`, we continue to look up via multihash key, but additionally query `state_cids` and fail if nothing is found 
2. Just verify completeness in `eth-ipfs-state-validator` instead (not sure if this is sufficient since it won't track the chain; maybe we could perform a similar state iteration in this service)
3. Something more complicated, like building a new EVM which can index nodes by leaf keys, or hacking Geth to do so

**Comment by i-norden** [comment]
Hey @roysc 

I think 1 or 3 are the approaches we need to take. `eth-ipfs-state-validator` will only verify the state in the ipfs blockstore and does a complete trie traversal so it is not feasible to do that every block.

I like the idea in 1, I think we should start with that and discuss the options for number 3 some more. The functionality in 3 would also potentially be useful for accelerating `eth_call` by having it access state and storage directly in `state_cids` and `storage_cids` rather than treating `public.blocks` like a geth levelDB.

**Comment by i-norden** [comment]
We will use: https://github.com/cerc-io/ipld-eth-statedb

**Comment by i-norden** [comment]
Closing this and replacing with issues for the new task of adding ipld-eth-statedb and the other remaining testing
